apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project-container
          image: ichrakmhiri1506/backend:latest
          ports:
            - containerPort: 8089
      imagePullSecrets:
        - name: regcred