apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-spring-boot
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend-spring-boot
  template:
    metadata:
      labels:
        app: backend-spring-boot
        env: prod
    spec:
      containers:
        - name: backend-spring-boot
          image: ichrakmhiri1506/backend:latest
          ports:
            - containerPort: 8089
          env:
            - name: DB_URL
              value: "jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true"
            - name: mysql_USER
              value: "root"
            - name: mysql_PASSWORD
              value: ""
            - name: mysql_DB
              value: "stationSki"
