apiVersion: v1
kind: Service
metadata:
  name: backend-spring-boot
spec:
  type: NodePort
  selector:
    app: backend-spring-boot
    env: prod
  ports:
    - name: test
      protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 32221