apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306  # Port MySQL par défaut
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: ""  # Mot de passe vide
            - name: MYSQL_DATABASE
              value: "stationSki"  # Nom de la base de données vide
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql/data
      volumes:
        - name: mysql-storage
          emptyDir: {}
