apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  mysql-root-password:  ''      # Le mot de passe root MySQL encodé en base64
  mysql-user-password:   ''     # Le mot de passe utilisateur MySQL encodé en base64
